### ISSUE TITLE
can't save map

### ISSUE THREAD

**Issue by gubuntu** [kartoza/geonode#216]
please fix

**Comment by gubuntu** [comment]
@boney-bun please test and close if fixed, provide feedback if not.

**Comment by gubuntu** [comment]
map does save but stays on the map creation screen with the Save button still active so the user gets the impression it has not saved. It should return to the map list page or the map view page for that map.

**Comment by boney-bun** [comment]
the map can't be saved at all in my local even though I logged as admin.
also, the UI doesn't react to the save button. 
i found few  issues that might be related to the save button on geonode.

**Comment by NyakudyaA** [comment]
@boney-bun  they are a couple of issues that are related to map creation. Perhaps you might want to look at them together as they might be related. I will reference all the map creation issues here so that you can work on them. #300, #299 , #298

**Comment by boney-bun** [comment]
that's a lot of issues @NyakudyaA 
i'll work into those issues
i guess i would start from this issue

**Comment by boney-bun** [comment]
i've got the below error message on the django console while running on my machine.
the error suggests there is a mismatch between model and database.
running `make sync` solved the problem (credit to @lucernae and @ismailsunni ).
i can save the map without any error.

do you want to try this on your local @NyakudyaA @gubuntu ?

i would close this ticket as it doesn't seem to be valid anymore.
feel free to reopen if the problem persist.

``` Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/src/app/geonode/maps/views.py", line 540, in new_map_json
    map_obj.update_from_viewer(body)
  File "/usr/src/app/geonode/maps/models.py", line 200, in update_from_viewer
    self.save()
  File "/usr/local/lib/python2.7/site-packages/polymorphic/models.py", line 90, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 771, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/src/app/geonode/qgis_server/signals.py", line 401, in qgis_server_post_save_map
    qgis_map, created = QGISServerMap.objects.get_or_create(map=instance)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 405, in get_or_create
    return self.get(**lookup), False
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "qgis_server_qgisservermap" does not exist
LINE 1: SELECT "qgis_server_qgisservermap"."map_id" FROM "qgis_serve... ```

**Comment by boney-bun** [comment]
@NyakudyaA i just noticed all these tickets ( #300, #299 , #298 , #303 , #304) are stil on the backlog. however, i would look at them.

**Comment by NyakudyaA** [comment]
@boney-bun  yes the issues are in the backlog because I created them now and they have not been moved to ready but some of them are bugs which I think needs to be addressed. I think the main issue with this ticket is that after saving the map the save button is still active even if the map has saved. I think the solution mentioned is that after saving the map the page should be redirected to geonode layer preview

**Comment by boney-bun** [comment]
i reopen this ticket.
to make it clear, here is what happened on my local @NyakudyaA:
![bug216](https://user-images.githubusercontent.com/4602383/28472928-d6d6c8a2-6e6c-11e7-8fe8-ce7d8b426fbe.gif)
on this GIF, leaving the user on this page will create many scenarios.
for example: the user can add more layers, delete layers, change extent, etc.
so, i propose a simple solution.
we can add a message telling that the map has saved, and disable the `save` and `add layer` buttons.
what do you think @NyakudyaA ?

**Comment by gubuntu** [comment]
No I think the behaviour looks fine and looks like normal GeoNode behaviour. Rather get this deployed on staging and ask people to test.

**Comment by boney-bun** [comment]
ok, so i'll close this ticket.
