### ISSUE TITLE
Can't add a new layer in the map on my local geonode

### ISSUE THREAD

**Issue by Gustry** [kartoza/geonode#99]
On geonode.kartoza.com, I can add a uploaded layer to a new map. 
However on my laptop, I can't add any layer, after a click on blue button `add layer`, nothing happened. In the console from django, I got : 

```
Call get layer
geonode:flood_laplata_2013_epsg4326
Get tiles url
Internal Server Error: /layers/geonode:flood_laplata_2013_epsg4326/get
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/etienne/kartoza_dev/web/geonode_app/geonode/layers/views.py", line 696, in get_layer
    ensure_ascii=False),
  File "/usr/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Decimal('-34.8645595463') is not JSON serializable
[11/Jun/2016 14:46:32] "GET /layers/geonode:flood_laplata_2013_epsg4326/get HTTP/1.1" 500 50144
```

**Comment by gubuntu** [comment]
@gustry pls comment or close

**Comment by Gustry** [comment]
Let's close this old ticket. I could replicate today.
